#!/bin/bash
# DOTFILES INSTALLER
#
# @Adri-md-1208
# adri.md.2001@gmail.com
# 2022

if [ "$(id -u)" -eq 0 ]; then
  echo -e "\e[31mRuning this script as root may make adverse changes in your system.\e[0m"
  echo -e "\e[31mPlease, run as non-root user\e[0m"
  exit 1
fi

# Message functions
error_msg() { 
  case "$1" in
    1)
      msg="Pacman error" 
      ;;
    2)
      msg="There is no $HOME directory"
      ;;
    3)
      msg="There is already a dotfiles repository"
      ;;
    4)
      msg="There is a trouble setting up the display manager"
      ;;
    *)
      msg="Unkown error"
      ;; esac
  printf "\e[31m\n[Error %d]\e[0m \e[33m%s\n\e[0m" "$1" "$msg" >&2
  exit 1
}

success_msg() {
  printf "\e[32m\n%s\n\e[0m" "$1"
}

informative_msg() {
  printf "\e[34m\n  %s\n\n\e[0m" "$1"
}

# UPGRADE AND SYNC PACMAN
informative_msg "Upgrading and syncing the repositories of pacman"
sudo pacman --noconfirm --needed --quiet -Syu 2> /dev/null || error_msg 1

# INSTALL PACKAGES
informative_msg "Installing necessary packages"
sudo cat pkgs.txt | sudo pacman --needed -Sy - || error_msg 1

# CREATE THE NECESSARY DIRECTORIES AND ENV VARIABLES
[ -e "$HOME" ] || export "$HOME=~/"
[ -d "$HOME"/.config ] || mkdir "$HOME"/.config

# DOWNLOADING THE DOTFILES GIT REPOSITORY
cd "$HOME" || error_msg 2
git clone https://github.com/Adri-md-1208/dotfiles.git 2> /dev/null || error_msg 3

# STOWING THE DOTFILES
informative_msg "Linking the dotfiles with your $HOME directory"
cd dotfiles
dotfiles=("qtile" "alacritty" "rofi" "zsh" "bash" "vim" "git" "Xresources")
for dotfile in "${dotfiles[@]}"; do
  stow --verbose "$dotfile"
done

# ENABLE DISPLAY MANAGER
sudo systemctl disable "$(grep '/usr/s\?bin' /etc/systemd/system/display-manager.service | awk -F / '{print $NF}')" || error_msg 4
sudo systemctl enable sddm
